apiVersion: v1
kind: ConfigMap
metadata:
  name: ks-metering-config
# namespace: kubesphere-system
data:
  ks-metering.yaml: |
    retentionDay: 7d
    billing:
      priceInfo:
        currencyUnit: "USD"
        cpuPerCorePerHour: 1.5
        memPerGigabytesPerHour: 5
        ingressNetworkTrafficPerGiagabytesPerHour: 3.5
        egressNetworkTrafficPerGigabytesPerHour: 0.5
        pvcPerGigabytesPerHour: 2.1